version: 0.2

env:
  variables:
    REGION: "ap-south-1"    # change region if needed

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "===> INSTALL PHASE"
      - java -version || true
      - mvn -v || true
      - echo "Working dir: $(pwd)"
  pre_build:
    commands:
      - echo "===> PRE_BUILD"
      - ls -la
  build:
    commands:
      - echo "===> BUILD: enter backend and package"
      - if [ ! -d "backend" ]; then echo "ERROR: backend folder missing" && exit 1; fi
      - cd backend
      - pwd
      - ls -la
      - mvn -B clean package -DskipTests
      - echo "mvn exit code: $?"
      - ls -la target || true
      - ART_JAR=$(find target -maxdepth 1 -type f -name "*.jar" | head -n 1)
      - if [ -z "$ART_JAR" ]; then echo "ERROR: No jar produced in backend/target" && exit 2; fi
      - echo "Found jar: $ART_JAR"
      - cp "$ART_JAR" ../backend.jar
  post_build:
    commands:
      - echo "===> POST_BUILD: packaging codedeploy artifact"
      - mkdir -p codedeploy_artifact
      - cp ../backend.jar codedeploy_artifact/backend.jar
      - cp backend/deploy/appspec.yml codedeploy_artifact/
      - cp -r backend/deploy/scripts codedeploy_artifact/
      - cd codedeploy_artifact
      - zip -r ../backend-codedeploy.zip .

artifacts:
  files:
    - backend-codedeploy.zip
