version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing backend build dependencies"
  build:
    commands:
      - echo "Building backend"
      - cd backend
      - mvn -B clean package -DskipTests
      - ART_JAR=$(ls target/*.jar | head -n 1)
      - cp "$ART_JAR" ../backend.jar
      - cd ..
  post_build:
    commands:
      - echo "Preparing CodeDeploy artifact zip"
      - mkdir -p codedeploy_artifact
      - cp backend.jar codedeploy_artifact/backend.jar
      - cp backend/deploy/appspec.yml codedeploy_artifact/
      - cp -r backend/deploy/scripts codedeploy_artifact/scripts
      - cd codedeploy_artifact
      - zip -r ../backend-codedeploy.zip .
artifacts:
  files:
    - backend-codedeploy.zip
